"""Database infrastructure and persistent records for the ReconcileFlow API."""

from .base import Base
from .database import Database
from .dependencies import DatabaseDependency, SessionDependency, get_database, get_db_session
from .errors import InvalidStatusTransitionError, PersistenceConflictError, PersistenceError, RecordNotFoundError, StorageQuotaExceededError
from .models import (
    AuditEventRecord,
    BACKGROUND_JOB_EVENT_TYPES,
    BACKGROUND_JOB_STATUSES,
    BACKGROUND_JOB_PRIORITIES,
    BackgroundJobRecord,
    BackgroundJobEventRecord,
    BackgroundJobPriority,
    BackgroundJobStatus,
    ConfigurationSnapshotRecord,
    MEMBERSHIP_ROLES,
    OrganizationMembershipRecord,
    OrganizationRecord,
    ReconciliationResultRecord,
    ReconciliationRunRecord,
    RefreshTokenRecord,
    SecurityAuditEventRecord,
    SourceFileRecord,
    UserRecord,
    WorkerRecord,
)
from .repositories import (
    AuditEventRepository,
    BackgroundJobEventRepository,
    BackgroundJobRepository,
    ConfigurationSnapshotRepository,
    OrganizationMembershipRepository,
    OrganizationRepository,
    Page,
    ReconciliationResultRepository,
    ReconciliationRunRepository,
    RefreshTokenRepository,
    SecurityAuditEventRepository,
    SourceFileRepository,
    UserRepository,
    WorkerRepository,
)
from .unit_of_work import PersistenceUnitOfWork

__all__ = [
    "AuditEventRecord",
    "AuditEventRepository",
    "BACKGROUND_JOB_EVENT_TYPES",
    "BACKGROUND_JOB_STATUSES",
    "BACKGROUND_JOB_PRIORITIES",
    "BackgroundJobRecord",
    "BackgroundJobEventRecord",
    "BackgroundJobEventRepository",
    "BackgroundJobPriority",
    "BackgroundJobRepository",
    "BackgroundJobStatus",
    "Base",
    "ConfigurationSnapshotRecord",
    "ConfigurationSnapshotRepository",
    "Database",
    "DatabaseDependency",
    "InvalidStatusTransitionError",
    "MEMBERSHIP_ROLES",
    "OrganizationMembershipRecord",
    "OrganizationMembershipRepository",
    "OrganizationRecord",
    "OrganizationRepository",
    "Page",
    "PersistenceConflictError",
    "PersistenceError",
    "PersistenceUnitOfWork",
    "RecordNotFoundError",
    "StorageQuotaExceededError",
    "ReconciliationResultRecord",
    "ReconciliationResultRepository",
    "ReconciliationRunRecord",
    "ReconciliationRunRepository",
    "RefreshTokenRecord",
    "RefreshTokenRepository",
    "SecurityAuditEventRecord",
    "SecurityAuditEventRepository",
    "SessionDependency",
    "SourceFileRecord",
    "SourceFileRepository",
    "UserRecord",
    "WorkerRecord",
    "UserRepository",
    "WorkerRepository",
    "get_database",
    "get_db_session",
]
