"""create initial persistence schema

Revision ID: 7da9a8e2e1ef
Revises: 
Create Date: 2026-09-06 01:44:35.897765
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '7da9a8e2e1ef'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reconciliation_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("status IN ('PENDING', 'RUNNING', 'SUCCEEDED', 'FAILED')", name=op.f('ck_reconciliation_runs_valid_status')),
    sa.CheckConstraint('finished_at IS NULL OR finished_at >= started_at', name=op.f('ck_reconciliation_runs_valid_time_range')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reconciliation_runs'))
    )
    op.create_index('ix_reconciliation_runs_status_created_at', 'reconciliation_runs', ['status', 'created_at'], unique=False)
    op.create_table('audit_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.CheckConstraint('sequence_number >= 1', name=op.f('ck_audit_events_positive_sequence')),
    sa.ForeignKeyConstraint(['run_id'], ['reconciliation_runs.id'], name=op.f('fk_audit_events_run_id_reconciliation_runs'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_events')),
    sa.UniqueConstraint('run_id', 'sequence_number', name='uq_audit_events_run_sequence')
    )
    op.create_index('ix_audit_events_run_occurred_at', 'audit_events', ['run_id', 'occurred_at'], unique=False)
    op.create_table('configuration_snapshots',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('amount_tolerance', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('date_tolerance_days', sa.Integer(), nullable=False),
    sa.Column('settings', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('amount_tolerance >= 0', name=op.f('ck_configuration_snapshots_nonnegative_amount_tolerance')),
    sa.CheckConstraint('date_tolerance_days >= 0', name=op.f('ck_configuration_snapshots_nonnegative_date_tolerance')),
    sa.ForeignKeyConstraint(['run_id'], ['reconciliation_runs.id'], name=op.f('fk_configuration_snapshots_run_id_reconciliation_runs'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_configuration_snapshots')),
    sa.UniqueConstraint('run_id', name=op.f('uq_configuration_snapshots_run_id'))
    )
    op.create_table('reconciliation_results',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('external_result_id', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('rule', sa.String(length=100), nullable=False),
    sa.Column('bank_source_record_ids', sa.JSON(), nullable=False),
    sa.Column('erp_invoice_ids', sa.JSON(), nullable=False),
    sa.Column('gateway_source_record_ids', sa.JSON(), nullable=False),
    sa.Column('expected_amount', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('actual_amount', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('amount_difference', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('requires_review', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("status IN ('EXACT_MATCH', 'SETTLEMENT_MATCH', 'TOLERANCE_MATCH', 'MANY_TO_ONE_MATCH', 'ONE_TO_MANY_MATCH', 'DUPLICATE', 'REQUIRES_REVIEW')", name=op.f('ck_reconciliation_results_valid_status')),
    sa.CheckConstraint('amount_difference IS NULL OR amount_difference >= 0', name=op.f('ck_reconciliation_results_nonnegative_difference')),
    sa.CheckConstraint('currency IS NULL OR length(currency) = 3', name=op.f('ck_reconciliation_results_valid_currency_length')),
    sa.ForeignKeyConstraint(['run_id'], ['reconciliation_runs.id'], name=op.f('fk_reconciliation_results_run_id_reconciliation_runs'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reconciliation_results')),
    sa.UniqueConstraint('run_id', 'external_result_id', name='uq_reconciliation_results_run_external_id')
    )
    op.create_index('ix_reconciliation_results_run_review', 'reconciliation_results', ['run_id', 'requires_review'], unique=False)
    op.create_index('ix_reconciliation_results_run_status', 'reconciliation_results', ['run_id', 'status'], unique=False)
    op.create_table('source_files',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=True),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('storage_key', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("source_type IN ('BANK_TRANSACTIONS', 'ERP_INVOICES', 'GATEWAY_SETTLEMENTS')", name=op.f('ck_source_files_valid_source_type')),
    sa.CheckConstraint('row_count IS NULL OR row_count >= 0', name=op.f('ck_source_files_nonnegative_row_count')),
    sa.CheckConstraint('size_bytes >= 0', name=op.f('ck_source_files_nonnegative_size')),
    sa.ForeignKeyConstraint(['run_id'], ['reconciliation_runs.id'], name=op.f('fk_source_files_run_id_reconciliation_runs'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_source_files')),
    sa.UniqueConstraint('run_id', 'source_type', name='uq_source_files_run_source_type')
    )
    op.create_index('ix_source_files_checksum_sha256', 'source_files', ['checksum_sha256'], unique=False)
    op.create_index(op.f('ix_source_files_run_id'), 'source_files', ['run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_source_files_run_id'), table_name='source_files')
    op.drop_index('ix_source_files_checksum_sha256', table_name='source_files')
    op.drop_table('source_files')
    op.drop_index('ix_reconciliation_results_run_status', table_name='reconciliation_results')
    op.drop_index('ix_reconciliation_results_run_review', table_name='reconciliation_results')
    op.drop_table('reconciliation_results')
    op.drop_table('configuration_snapshots')
    op.drop_index('ix_audit_events_run_occurred_at', table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index('ix_reconciliation_runs_status_created_at', table_name='reconciliation_runs')
    op.drop_table('reconciliation_runs')
    # ### end Alembic commands ###
